### ISSUE TITLE
/lib/index.js missing

### ISSUE THREAD

**Issue by minomy13** [dufourgilles/knx-ip#15]
Hello, if I start my app, I am getting the following error:

`internal/modules/cjs/loader.js:311
      throw err;
      ^

Error: Cannot find module 'C:\Users\max\Documents\KNX\Panel\first test\node_modules\knx-ip\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\adria\Documents\KNX\Panel\first test\app.js:1:51)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\max\\Documents\\KNX\\Panel\\first test\\node_modules\\knx-ip\\package.json',
  requestPath: 'knx-ip'
}`

Can you please help me?

**Comment by minomy13** [comment]
Okay, sorry, I've said "if I start my app" but I meaned the example app which i've taken from the readme...

**Comment by dufourgilles** [comment]
Thanks you for reporting the issue.
The latest package was corrupted.
Please test 0.1.13

**Comment by minomy13** [comment]
Now it says: KNXClient.startDiscovery is not a function :(

**Comment by dufourgilles** [comment]
I tested Windows 10, MacOS, and Ubuntu.
It works on all of them with a copy-paste of the example.
Tested Node 10 and Node 12.

![image](https://user-images.githubusercontent.com/16135147/103435830-a8cd0f00-4c14-11eb-9a18-10edfdbe9c09.png)
